### ISSUE TITLE
我确定拉的是这边的仓库。

### ISSUE THREAD

**Issue by Yummy-cookie** [CikeyQi/QQsign_docs#10]
![Image_1703689936274](https://github.com/CikeyQi/QQsign_docs/assets/114837513/0bb56a33-d6ea-4e83-8e3b-6d2209773961)

**Comment by wudifeixue** [comment]
Error: Unable to initialize main class MainKt
Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope

我也出现这个情况了，
复现步骤：
1. `git clone https://github.com/CikeyQi/QQsign_docs.git`
2. `docker build -t qqsign .`
3. `docker run -p 8080:8080 -e TXLIB_VERSION=8.9.93 qqsign`

然后就报错了

**Comment by Nats-ji** [comment]
不知道为啥我在windows上测试的时候可以，但是换到服务器上就这样报错

**Comment by CikeyQi** [comment]
Try Again！
