### ISSUE TITLE
根据文档配置后，等待运行时，页面跳转报错

### ISSUE THREAD

**Issue by sapphire159** [CikeyQi/QQsign_docs#12]
我们无法为您提供对 Koyeb 的访问权
您的帐户与通常与违反我们[服务条款](https://www.koyeb.com/docs/legal/terms)相关的模式相匹配。
虽然我们无法提供有关触发此行为的原因的详细信息，但我们已经确定无法提供对 Koyeb 的访问权限。

原文
We cannot offer you access to Koyeb
Your account matches patterns often associated with violations of our [Terms of Service](https://www.koyeb.com/docs/legal/terms).
While we cannot provide details about the reason(s) triggering this behavior, we have determined that providing access to Koyeb is not possible.

If you believe this is a bug, you can validate your account.

登陆后只有此界面，账户被封禁，试过注册两次均为此情况。

**Comment by CikeyQi** [comment]
那就用自己的邮箱注册试试
