### ISSUE TITLE
Build error Error while cloning Space repository

### ISSUE THREAD

**Issue by AltinaSchwarzer** [CikeyQi/QQsign_docs#4]
![image](https://github.com/CikeyQi/QQsign_docs/assets/107377630/ee6898c9-203f-4ba5-b022-12d470ba07b7)
![image](https://github.com/CikeyQi/QQsign_docs/assets/107377630/97ba0d0a-eecc-4562-b47b-8520f0cad962)

出现z这个问题

**Comment by AltinaSchwarzer** [comment]
![image](https://github.com/CikeyQi/QQsign_docs/assets/107377630/4ccd197d-2de6-4a60-bf1b-fbc59a700bbe)

**Comment by CikeyQi** [comment]
请确认填入的版本号是否被支持
