### ISSUE TITLE
填写错版本号了，能否删除重建呢

### ISSUE THREAD

**Issue by flyfox2015** [CikeyQi/QQsign_docs#5]
大佬，我设备版本是8.9.73，但我在生成时填写成8.9.68，但只能建一次，能否删除8.9.68，重新生成8.9.73呢？

**Comment by CikeyQi** [comment]
可以，在自己的空间点击Settings，找到Variables and secrets，找到TXLIB_VERSION，点Replace，填入新的版本号即可
