### ISSUE TITLE
进去就一直building

### ISSUE THREAD

**Issue by znc15** [CikeyQi/QQsign_docs#7]
![image](https://github.com/CikeyQi/QQsign_docs/assets/64775575/e906a941-d83b-4bb7-87e1-60e34922d640)
![image](https://github.com/CikeyQi/QQsign_docs/assets/64775575/7f19f22a-34fd-4e84-93e5-f2bc5fb673cd)

**Comment by CikeyQi** [comment]
这是HuggingFace那边的问题，建议等待一段时间后再试
